GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/6a8a6634243f4c23a456545c

###
DELETE  http://localhost:3001/api/persons/6a8a649c1cbbdf0fc20de024

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "domo",
    "number": "044-567890"
}

### 
PUT http://localhost:3001/api/persons/6a8a6634243f4c23a456545c
Content-Type: application/json

{
    "name": "domo",
    "number": "098-567890"
}